name: paypulse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: 6.0.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.1
  dio: ^5.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  equatable: ^2.0.5
  connectivity_plus: ^6.0.0
  encrypt: ^5.0.3
  dartz: ^0.10.1
  web3dart: ^2.7.3
  http: ^1.2.0
  path: ^1.9.1
  firebase_analytics: ^12.1.0
  firebase_messaging: ^16.1.0
  local_auth: ^3.0.0
  flutter_local_notifications: ^19.5.0
  sqflite: ^2.4.2
  ml_algo: ^16.18.0
  ml_dataframe: ^1.6.0
  ml_preprocessing: ^7.0.2
  pointycastle: ^3.9.1
  asn1lib: ^1.6.5
  fl_chart: ^0.66.1
  json_annotation: ^4.8.1
  logger: ^2.6.2
  permission_handler: ^12.0.1
  flutter_contacts: ^1.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  mocktail: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
