name: paypulse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: 6.0.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.1
  dio: ^5.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  equatable: ^2.0.5
  connectivity_plus: ^6.0.0
  # Features
  fl_chart: ^0.66.1
  flutter_local_notifications: ^19.5.0
  sqflite: ^2.4.2
  json_annotation: ^4.8.1
  logger: ^2.6.2
  telephony: ^0.2.0
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9+2
  qr_flutter: ^4.1.0
  flutter_animate: ^4.5.0
  mobile_scanner: ^7.1.4
  image_picker: ^1.2.1
  firebase_storage: ^13.0.5
  firebase_analytics: ^12.1.0
  firebase_messaging: ^16.1.0
  local_auth: ^3.0.0
  dartz: ^0.10.1
  path: ^1.9.1
  intl: any
  encrypt: ^5.0.3
  uuid: ^4.5.2
  pdf: ^3.11.3
  printing: ^5.14.2
  smooth_page_indicator: ^2.0.1
  google_fonts: ^6.3.3
  sensors_plus: ^7.0.0
  confetti: ^0.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  mocktail: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
